default_language_version:
    python: python3.11
default_stages: [commit]
repos:
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: hatch run test
      language: system
      # stages: [push]
      types: [python]
      pass_filenames: false
      always_run: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    # - id: trailing-whitespace
    # - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    # - id: check-yaml
    - id: check-toml
    - id: check-json
    - id: detect-private-key
    - id: forbid-new-submodules
    # - id: check-added-large-files
# https://pre-commit.com/hooks.html
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.10.0
  hooks:
    - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.6.1
  hooks:
    - id: mypy
      # args: [--ignore-missing-imports]
      additional_dependencies: [mkdocs]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.1
  hooks:
    - id: ruff

- repo: https://github.com/commitizen-tools/commitizen
  rev: 3.12.0
  hooks:
    - id: commitizen
      stages: [commit-msg]
      additional_dependencies: [typing-extensions]
